defaults:
  - config
  - _self_

log_root_prefix: ./magicdrive-log/test

# 每次验证使用4个样本？
runner:
  validation_batch_size: 4

resume_on_exists: false
show_box: true

fix_seed_for_every_generation: False
